# Generated by Django 4.0.6 on 2024-01-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_deviceperipheral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceperipheral',
            name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='peripherals',
            field=models.ManyToManyField(to='pages.deviceperipheral'),
        ),
    ]
