# Generated by Django 4.0.6 on 2024-01-24 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_read_created_at_read_peripheral_read_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='peripheral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.deviceperipheral'),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.device'),
        ),
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
